### ISSUE TITLE
Contador de total en LineaMuestras::add() desvaría

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#1]
Cuando se añaden muchas cribas con decimales, el contador de total desvaría en LineaMuestras::add(). Acabamos con totales de 99,99999999% en lugar de 100%
Incluso a veces se muestra 100% pero el modelo se queja como si no fuera 100% y no deja guardar.

**Comment by rodolgl** [comment]
En mi Win 8.1 parece que está todo correcto.

**Comment by rodolgl** [comment]
Al rellenar una muestra me ha dado un error del Controller: 
 \app\Controller\LineaMuestrasController.php (line 59)

array(
	'marca' => 'Una marca',
	'numero_sacos' => '1223',
	'humedad' => 'Poca',
	'tueste' => 'Medio',
	'referencia_proveedor' => '10/112',
	'referencia_almacen' => '11/33',
	'apreciacion_bebida' => 'Rica',
	'defecto' => 'Muchos',
	'muestra_id' => '15'
)

\app\Controller\LineaMuestrasController.php (line 60)

(int) 0

**Comment by eBug** [comment]
Creo que esta solucionado. Si vuelve a ocurrir, reabrimos la incidencia.

**Comment by eBug** [comment]
A día de hoy seguimos teniendo problema al sumar los float en javascript
