### ISSUE TITLE
en todos los formularios de add o edit, meter un botón de 'Cancelar'

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#124]

**Comment by eBug** [comment]
http://articles.classoutfit.com/cakephp-add-a-cancel-link-to-add-and-edit-form/

**Comment by rodolgl** [comment]
Ya lo tengo. 
	echo $this->Html->link('Cancelar', $this->request->referer(''), array('class' => 'botond'));
¡Ahora a meterlo en todas partes!

**Comment by eBug** [comment]
Si tuvieramos un Common/edit.ctp, sólo haría falta meterlo una vez...

**Comment by rodolgl** [comment]
Cuando entienda los problemas generado al crear el form y no me de errores el edit, modifico todos los formularios de la aplicacion.

**Comment by rodolgl** [comment]
Se crea element-> cancelarform y se incluye en todos los formularios.De este modo podemos modificar el elemento y asignarle las características adecuadas para tenerlo bien implementado.
