### ISSUE TITLE
Generar informe de linea de muestra 

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#14]
Ver la copia que entregó Carlos 'Informe de calidad'

**Comment by rodolgl** [comment]
Está en ello, pero falta arreglar la generación de PDFs

**Comment by rodolgl** [comment]
Para la generación de PDFs es necesario un complemento. Si se va a alojar la máquina en kona (gnu/linux) podría ya trabajarse en agregar ese plugin aunque no estuviera maquetado.

**Comment by rodolgl** [comment]
Relacionado directamente con  #315. Se cierra.
