### ISSUE TITLE
Corregir los redirect en los controladores dependiendo de la tabla a modificar

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#149]
Contactos funciona bien a la hora de agregarlo si viene de una view pero no puede usarse directamente con contactos/add porque no hay parámetros. 
Esos errores hay que ir modificandolos en el controlador como alternativa si no hay parámetros de donde viene.

**Comment by eBug** [comment]
@rodolgl es que no se pueden agregar contactos directamente. Siempres son contactos de una empresa.

**Comment by rodolgl** [comment]
Comentado ayer. Los problemas son de la anidaciones. Solución popup. Se cierra
