### ISSUE TITLE
en Muestras::view() no sale el botón de editar

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#157]
Además los otros estan solapados

**Comment by eBug** [comment]
Esta parcialmente solucionado, salen los botones, hay que tomar una decisión de diseño a saber si todos los botones de borrar salen con texto 'borrar' o no. Por ejemplo,
http://cake-cmpsa.gargantilla.net/linea_muestras/view/18/from_controller:muestras/from_id:10
http://cake-cmpsa.gargantilla.net/agentes/view/126

según hay o no un from_controller, cambia el boton en Helper/ButtonHelper.php

**Comment by rodolgl** [comment]
Esto sigue así o se solucionó?

**Comment by eBug** [comment]
Aquí me sale bien dicho botón
