### ISSUE TITLE
En Operaciones::add() salen descuadrados los campos del formulario

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#162]
Esta todo patas arriba.

**Comment by rodolgl** [comment]
Como comenté en el commit anterior. Hay que hacer una hoja de estilo concreta para los formularios con clases centradas en los campos más utilizados.

**Comment by rodolgl** [comment]
Se ha dejado bastante bien. Si te gusta lo hago en el edit.

**Comment by rodolgl** [comment]
Hecho en trafico.
