### ISSUE TITLE
Corregir formulario de Muestras::add()

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#172]
Estan los campos de formulario descuadrados.

me parece que sería más legible tener:
Registro: <      >
Contrato: <      >
Calidad:<         >
etc... que
Registro
<         >
Contrato
<         >
Calidad
<          >

o hacer una columna a la izquierda con los campos y otra a la derecha con las incidencias, así si el número de campos de la izquierda fuera variable, no se descuadraría todo el formulario.

**Comment by rodolgl** [comment]
Ahora está perfecto
