### ISSUE TITLE
Al borrar cualquier elemento, la ventana emergente de confirmacion no da la información esperada

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#18]
Esto del [object][object] al borrar algo pasa con todo, tanto los contactos, como las muestras o las lineas de cata

**Comment by eBug** [comment]
Mirar:
http://book.cakephp.org/2.0/en/core-libraries/helpers/form.html#FormHelper::postLink

**Comment by rodolgl** [comment]
Está relacionado con array('class'=>'boton') que genera error al introducirlo al postlink. Sigo investigando

**Comment by eBug** [comment]
commit 93e6bb902c727a0561df990baa18e1b2d138cadb
