### ISSUE TITLE
En Transportes::add() meter la referencia de la operacion

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#182]
Añadir Transporte a Operación ... seria bien saber qué operacion

**Comment by rodolgl** [comment]
![captura](https://cloud.githubusercontent.com/assets/8113818/12114552/12168c1e-b3ab-11e5-96d2-dd83d1f3c346.JPG)
¿?

**Comment by rodolgl** [comment]
![captura](https://cloud.githubusercontent.com/assets/8113818/12114578/39f84c86-b3ab-11e5-911d-5925f244aa6f.JPG)
¿?

**Comment by rodolgl** [comment]
Se ve en la rama Tráfico. Cierru!

**Comment by eBug** [comment]
Parece que no sale en cake-cmpsa:muestras. Ya esperaré el merge
