### ISSUE TITLE
operacion (view) embarque/entrega, campo a añadir

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#199]
Se solicita agregar Embarque/entrega fecha en la vista de operación desde Compras.

**Comment by eBug** [comment]
duplicate #52

**Comment by eBug** [comment]
Crear un virtualField para Contrato que sea embarque/entrega + mes(?)/año 
Para contabilidad, en Financiaciones, solo sale el año, les vale a las chicas de compra ?
