### ISSUE TITLE
Falla Retirada::add()

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#204]
Al guardar el formulario, da un pete en todos los campos ;(
http://cake-cmpsa.gargantilla.net/retiradas/view/89

**Comment by rodolgl** [comment]
En la fecha, solo permitir la actual o la pasada en un año. Cambiar el nombre de embalaje por sacos.

**Comment by rodolgl** [comment]
Arreglado lo de la fecha y cambiado el nombre.

**Comment by rodolgl** [comment]
Ahora hay que poner Asociados y Almacen transporte bien junto con el javascript.

**Comment by rodolgl** [comment]
Bueno, ahora guarda pisando la información de lo que había anteriormente. Dioooos
