### ISSUE TITLE
contactos/edit(), proveedor y bancos view()

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#220]
Error de from_id y from_controller
![error](https://cloud.githubusercontent.com/assets/8113818/12957003/09ca19bc-d02b-11e5-94a7-50e9d6e7ada0.JPG)

**Comment by eBug** [comment]
esto pasa cuando entras directamente a los contactos ?

**Comment by eBug** [comment]
Lo que tengo ahora es que sí puedo editar contactos de un banco, pero no puedo añadir contactos nuevos...

**Comment by eBug** [comment]
![screenshot from 2016-02-18 21-46-58](https://cloud.githubusercontent.com/assets/2424036/13157614/3892516a-d689-11e5-8b68-51760cd3d223.png)
