### ISSUE TITLE
al añadir una retirada desde Operacion:view_trafico() se guarda la retirada, pero no aparece en el resumen de retiradas

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#221]

**Comment by eBug** [comment]
Eso parece que pasa porque al guardar la retirada, no guarda la id de la operacion. Se comprueba que en Retirada::index() esta la retirada pero que no tiene operacion.

**Comment by rodolgl** [comment]
Hay que filtrar el asociado en el form() para que coincida con los que están en la operación porque sino al agregar un asociado que no está en la operación y no va a salir nunca.

**Comment by eBug** [comment]
Aunque este el asociado en la operación, no aparece su retirada en el
resumen. Sí aparece en retirada::index()

**Comment by rodolgl** [comment]
Es la opción 'disabled' que deshabilita por completo la variable, en vez de simplemente no dejar modificarla como pretendía. Solucionado.

**Comment by eBug** [comment]
@rodolgl creo recordar que los campos de un formulario que estan 'disabled' no se incluyen en $this->request->data
