### ISSUE TITLE
al añadir una retirada desde Operacion::view_trafico(), que solo salgan los socios de dicha operacion en el desplegable

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#222]
Ahora mismo salen todos los socios en el desplegable. Si se despistan acaban metiendo una retirada a un socio que no esta en la operacion.

**Comment by rodolgl** [comment]
Falta cuenta de almacen. Está hecho aunque hay algún matiz que se me escapa.

**Comment by rodolgl** [comment]
Se cierra #204. Seguimos aquí

**Comment by rodolgl** [comment]
Esto lo arreglamos ayer con @eBug
