### ISSUE TITLE
imposibilidad de borrar línea de transporte si hay cuenta de almacén transportes view() delete

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#229]
No borra en cascada las líneas de almacenes una vez que se pretende eliminar una línea de transporte
Error: SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`cmpsa_migration`.`almacen_transportes`, CONSTRAINT `fk_almacenes_has_transportes_transportes1` FOREIGN KEY (`transporte_id`) REFERENCES `transportes` (`id`) ON DELETE NO ACTION ON UPDATE NO A)

**Comment by eBug** [comment]
@rodolgl hay algun problema para activar el ON DELETE CASCADE en la BDD ?

**Comment by rodolgl** [comment]
Arreglado maestro.
