### ISSUE TITLE
En Muestras::add() los campos de fecha estan descuadrados

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#23]
No salen en la misma linea

**Comment by rodolgl** [comment]
Se cuadran todos, sin embargo no sé de donde sale la siguiente hoja de estilo y si es necesaria
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">

**Comment by eBug** [comment]
Pues a mi me salen descuadrados

**Comment by eBug** [comment]
En 
http://cake-cmpsa.gargantilla.net/muestras

no estan cuadrados

**Comment by eBug** [comment]
Estoy ciego... Se pueden juntar día, mes y fecha?

**Comment by rodolgl** [comment]
Se puede se puede. Voy a ello.

**Comment by rodolgl** [comment]
Esto ya está solucionado.

**Comment by eBug** [comment]
Pues no.

**Comment by rodolgl** [comment]
Hasta que no se solucione el desplegable/buscador de javascript no es recomendable cuadrarlo, aunque yo lo veo ya correctamente.

**Comment by rodolgl** [comment]
Solventado. Se ve bien. El formulario se reorganiza
