### ISSUE TITLE
Al borrar una retirada desde Retiradas::view_asociado() el redirect esta mal

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#239]
Por ejemplo:
http://cake-cmpsa.gargantilla.net/retiradas/view_asociado/asociado_id:75/from_controller:operaciones/from_id:140

Se borra bien la retirada, pero después de borrar, el redirect se hace a la view de la retirada que se acaba de borrar, dando un pete muy feo (intentando mostrar la view de una retirada que ya no existe).

**Comment by rodolgl** [comment]
Esto ya está solventado. Confirmado proximo commit
