### ISSUE TITLE
El enlace a la operación en Retirada::view_asociado() esta mal

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#240]
http://cake-cmpsa.gargantilla.net/retiradas/view_asociado/asociado_id:75/from_controller:operaciones/from_id:140
Entiendo que si pincho en el enlace de la operacion, debería llevarme a operaciones/view_trafico y no a operaciones/view

**Comment by rodolgl** [comment]
Esto ya está solventado.
