### ISSUE TITLE
Al modificar la retirada de un asociado, vuelve a la operacion cuya id es el id del asociado

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#241]
http://cake-cmpsa.gargantilla.net/retiradas/view_asociado/asociado_id:75/from_controller:operaciones/from_id:140
Si modifico una retirada, al guardar la retirada modificada, me redirige a una view de operación que no tiene nada que ver. la retirada modifica sí se guarda.

**Comment by rodolgl** [comment]
Esto está bien. El problema es otro que abriré ahora un issue.
