### ISSUE TITLE
No se puede modificar una linea de almacen desde Transporte::view()

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#242]
Entiendo que los botones de editar en el apartado 'Almacenes' tienen el enlace mal.

http://cake-cmpsa.gargantilla.net/transportes/view/96/from_controller:operaciones/from_id:140

Error: AlmacentransportesController could not be found.

**Comment by rodolgl** [comment]
¿Esto lo has hecho con la ultima versión de tráfico? A mi me entra bien

**Comment by rodolgl** [comment]
Esto funciona bien en la rama tráfico de hoy.
