### ISSUE TITLE
Error de BBDD en operaciones y transporte!!!

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#248]
Si una operación no tiene almacen transporte 
![captura](https://cloud.githubusercontent.com/assets/8113818/13527011/3becb13c-e20c-11e5-9d26-646ea71c8c3c.JPG)

**Comment by eBug** [comment]
eso esta arreglado en la rama facturacion.

**Comment by rodolgl** [comment]
Cerrado
