### ISSUE TITLE
Al editar la retirada de un socio, las cantidades salen mal en el formulario

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#254]
http://cake-cmpsa.gargantilla.net/retiradas/view_asociado/asociado_id:75/from_controller:operaciones/from_id:140
Puedo editar culaquiera de las dos retiradas, me salen valores que no son las que estaban guardadas en el formulario de edicion.

**Comment by eBug** [comment]
Es el #247?

**Comment by rodolgl** [comment]
Sí pero ya está solucionado. Ahora a vamos hacer mejoras posibles en el comportamiento. Cierro también el #247
