### ISSUE TITLE
Error al editar Contacto

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#258]
lEl contacto se guarda pero no redirecciona bien.

Missing Controller

Error: ViewController could not be found.

Error: Create the class ViewController below in file: app\Controller\ViewController.php

**Comment by eBug** [comment]
Dame una URL de ejemplo porque así no se entiende del todo. Quieres añadir un contacto desde Contacto::index() ?

**Comment by rodolgl** [comment]
Hay un error en cake-cmpsa/contactos/index porque al **modificar **surgen los problemas de:
Notice (8): Undefined index: from_controller [APP\View\Contactos\form.ctp, line 9]
Notice (8): Undefined index: Empresa [APP\View\Contactos\form.ctp, line 10]
Notice (8): Undefined index: from_controller [APP\View\Contactos\form.ctp, line 10]
Notice (8): Undefined index: from_id [APP\View\Contactos\form.ctp, line 10]

A la hora de agregar ahora mismo no encontré errores. Tendría que investigar.
