### ISSUE TITLE
fallo en muestras index()

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#259]
Si se entra desde datos> muestras index() da error por la variable Search.tipo_id al ser null. Se debe contemplar que se pueda entrar por ahí si no hay valor en la variable.

**Comment by eBug** [comment]
Yo quitaría de gestiondatos, todo lo que esta duplicado con los menús de arriba, como Contactos, Muestras, Contratos, Operaciones, sólo dejando lo que no tiene cabida arriba, como IVA, Empresas, Embalajes, etc.

**Comment by rodolgl** [comment]
Esto es cierto. Si te parece lo cambio todo ahora y te cierro este issue. Me lo asigno.

**Comment by rodolgl** [comment]
Hecho
