### ISSUE TITLE
operaciones siempre añadir cantidad bultos

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#266]
Si al crear una operación no se obliga a que se introducza una cantidad, cuando salimos del formulario luego falla todo. 

Warning (2): ksort() expects parameter 1 to be array, null given [APP/Controller/OperacionesController.php, line 674]

**Comment by rodolgl** [comment]
Falla en operacion (view)

**Comment by eBug** [comment]
Hay que preguntar a las chicas de compra si quieren tener la posibilidad de crear una operacion 'en blanco', sin cantidad.
Si quieren operaciones 'en blanco', entonces hay que meter un test antes del ksort en el código.

**Comment by eBug** [comment]
sí hay que contemplar que puedan grabar una operación, aún sin meter reparto.

**Comment by eBug** [comment]
El problema es al abrir la vista de una operación que no tiene asociados:
http://cake-cmpsa.gargantilla.net/operaciones/view/192
no hay nada para rellenar las líneas.
