### ISSUE TITLE
Al modificar una retirada, en el formulario, cambia el asociado y al guardar se asigna la retirada a otro asociado

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#281]
Por ejemplo,
http://cake-cmpsa.gargantilla.net/retiradas/view_asociado/asociado_id:75/from_controller:operaciones/from_id:140
si hago clic en el botón 'editar' de la retirada de Baqué, se abre el formulario como retirada de Tupinamba

**Comment by rodolgl** [comment]
Comprobado. Curioso. Lo chequeo ahora.

**Comment by eBug** [comment]
también cambia la cuenta corriente.

**Comment by rodolgl** [comment]
Esto pasa también al añadir desde asociados_view. El problema es con el 'id' => 'asociado', si lo descomento funciona tal como debe, pero al hacerlo evito que funcione la función de javascript para almacenes. Hay que pensar una solución.

**Comment by rodolgl** [comment]
Ya sé el error, en vez de asignarle la id del asociado, hay que asiganrle el value 0,1,2... del array.

**Comment by rodolgl** [comment]
Parece que ya está solucionado.
