### ISSUE TITLE
error con el botón de imprimir

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#282]
Undefined variable: id [APP/View/Elements/imprimirV.ctp, line 7] por lo menos en:
http://cake-cmpsa.gargantilla.net/facturaciones/view/140

**Comment by rodolgl** [comment]
Bastante normal si eso no está ni en la rama Test! Se puede hacer un merge de facturación a test?

**Comment by rodolgl** [comment]
Solventado en rama test.
