### ISSUE TITLE
al borrar una retirada, volver al detalle de retiradas del asociado en la operacion

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#284]

**Comment by rodolgl** [comment]
Esto se soluciona haciendo un editCrossed y un deleteCrossed para arrastar la id del asociado, tal como está en el viewCrossed en bottonhelper.

**Comment by rodolgl** [comment]
En esto necesito ayuda/opinión sobre cómo solventarlo, porque hasta ahora las pruebas que hago me fallan.

**Comment by eBug** [comment]
Revisar todo el codigo y empezar a usar HistoryComponent
