### ISSUE TITLE
Cuentalalmacen no carga bien en form() retiradas

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#290]
Se solucionó con asociado, ahora es con almacén. Hay que mirarlo.

**Comment by rodolgl** [comment]
<script type="text/javascript">
window.onload = operacionesRetirada();
</script> Si lo vuelves a comentar funciona almacen al cargar desde cero. Si seleccionas una operacion funciona. Pero desde que accedes no queda asignada.

**Comment by eBug** [comment]
@rodolgl No queda asignada a qué?

**Comment by rodolgl** [comment]
Perdón. Si descomentas de nuevo <script type="text/javascript">window.onload = operacionesRetirada();
</script>
Almacén carga bien al principio, pero asociados no va, si lo dejas comentado, almacenes no va al cargar por primera vez la página. 
Hablo del FORM () retiradas

**Comment by rodolgl** [comment]
Se solventa.
