### ISSUE TITLE
Fallo al anyadir linea de transporte

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#299]
Undefined variable: num [APP/Controller/TransportesController.php, line 406]
http://gestion.cmpsa.com/transportes/add/from_controller:operaciones/from_id:29

**Comment by rodolgl** [comment]
Esto está solucionado. Sólo falta que decidan qué valor quieren que tengan las líneas a la hora de borrarlas. Mantener el valor o siempre contar desde el principio.
