### ISSUE TITLE
vista nueva almacenes_retiradas()

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#312]
Acceder a una vista donde se asignen la distribución de los bultos por almacén que han sido solicitados por los asociados. Al estilo operaciones edit.

**Comment by rodolgl** [comment]
-Tras guardar almacén -> distribución asociados por sacos -> esa vista muestra la distribución porcentual de los sacos correspondientes.
Ejemplo: linea 1 - 35 sacos / linea 2 - 400 sacos

- Con un botón de poder modificar e ir a algo similar a operación edit()

- Después se pasa a los socios, botón imprimir un pdf (ver hoja

s)

**Comment by rodolgl** [comment]
Cerrado por error.
Al guardar, llevar a la vista la distrubución de asociados por línea. la distribución es por cantidad actual total almacenada por cuenta de almacén.

**Comment by rodolgl** [comment]
Se va a crear una view en almacen_transportes. Se crea botón de Detalle en cada cuenta corriente desde transporte view().
Dentro de la vista de almacen_transporte se verá la info de la cuenta corriente que pertenece, al estilo de las demás vista y el desglose inferior de los asociados (habrá que ver si todos o sólo los pertenecientes a la operación). Desde ahí se podrá modificar o borrar la cuenta corriente, si y solo si no hay ninguna retirada. Seguiremos actualizando.

**Comment by rodolgl** [comment]
Procedimiento:
1.Asociado_operaciones. Saco el porcentaje de cada uno en la retirada que le recorresponde. 
2. con esas variables adquiridas.muestro una vista con la lista de asociados y la cantidad de sacos que le corresponde.
3.¿las retiradas deben estar controladas para que no se lleven más de lo asignado?en principio NO.
4.¿Crear nueva tabla o gestionarlo desde el código? En principio desde el código.
5. Vista con la posibilidad de cambiar la cantidad de sacos con todos los asociados (no solo lo de la operación) y visualizar con javascript la desviación del porcentaje respecto a lo que le correspondería, tal como está en añadir operación general.

**Comment by eBug** [comment]
@rodolgl Creo que va más directo sacar el porcentaje directamente de mysql con campo virtual o view

**Comment by rodolgl** [comment]
Cierro esto porque ya esta hecho. Lo que tengo que hacer es un nuevo issue con el informe para los asociados de la cantidad concreta.
