### ISSUE TITLE
Función envío emails informes laboratorio

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#315]
1. Sólo funciona la impresión en la ENTREGA, quitar los botones de pdf e impresion en oferta y embarque.
2. Un botón lateral para enviar el informe. Referencia, A, ATN y Observaciones -> éste funciona diferente al campo observación de la BBDD de la linea de muestra . Debe ser una var string.
3. Botón vista previa del informe. cerrar
4. Enviar x mail. Agenda laboratorio seleccionada. Asubnto, texto y adjuntoautomaticos. Envío con BCC a tráfico siempre.

**Comment by rodolgl** [comment]
Está todo montado pero falla la asignación de las variables.

**Comment by rodolgl** [comment]
Se debe crear un pdf con el informe cada vez que se guarde una nueva linea de muestras. Hay que definir la ruta donde se hará y cómo. Es necesario para poder luego adjuntarlo por correo. La verdad que exactamente como lo piden me parece un exceso de complicación si no hay una tabla de la BBDD detrás.

**Comment by rodolgl** [comment]
Quitar referencia de provedor en entrega.
Eliminar asunto. dejar uno por defecto,  Informe de calidad (registro muestra) / (referencia operación)
Eliminar mensaje. dejar uno por defecto

El campo de referencia hacer un text como campo.

**Comment by rodolgl** [comment]
Se ha creado correo calidad@cmpsa.com y funciona correctamente, se ha mejorado la configuración del email. Ahora necesito generar automáticamente los PDF pero por ahora no encuentro documentación y la que encontré no me funciona.

**Comment by rodolgl** [comment]
- Envío de correos correcto.
- Se cambia la asignación de los campos a los de la tabla lineamuetras en vez de la virtual.
- Falta guardar y recargar la información en pdf
-Falta generar el pdf en el disco para enviar.
De esto queda ya poco si no surgen problemas.

**Comment by rodolgl** [comment]
Atascado con la descarga de pdf. Hay que seguir dándole una vuelta.
![seleccion_002](https://cloud.githubusercontent.com/assets/8113818/15541241/dcd658a4-228b-11e6-8573-9204817f4817.jpg)

**Comment by rodolgl** [comment]
Ya guarda los PDF con la plantilla, falta que cargue los datos y parece ser que es por algo relacionado con los permisos y el usuario 'daemon'. Luego tengo problemas al adjuntar porque si pongo la ruta en la configuración genérica lo hace, si lo hago desde donde me interesa, en el controlador. Lo ignora a pesar de enviar el correo adecuadamente. Es de traca.

**Comment by rodolgl** [comment]
Se cierra que no me cierra desde el commit.

**Comment by eBug** [comment]
@rodolgl El commit se cierra cuando llega a test
