### ISSUE TITLE
Alinear en tablas campos numéricos a la derecha

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#336]
table tr td {
	padding: 0.5% 0.5% 0.5% 1%;
**	text-align: justify o center**
	vertical-align: top;
	border-bottom:1px solid #ddd;
}

**Comment by rodolgl** [comment]
Incluso te diría align: right!

**Comment by eBug** [comment]
@rodolgl alineación a la derecha me parece lógico para campos numéricos. Para texto, es mas habitual alineacion izq.

**Comment by rodolgl** [comment]
@eBug  pues entonces estamos jodidos. Porque a nivel general hay que elegir. Lo dejo así y donde haya campos numéricos alineamos uno a uno a la derecha. Entonces esto lo dejo como pendiente para la versión final y me lo asigno. Cambio el titulo.

**Comment by eBug** [comment]
@rodolgl no soy especialista de css pero creo que sí hay soluciones:

**Comment by eBug** [comment]
@eBug http://stackoverflow.com/questions/4458131/is-there-a-way-to-set-the-text-alignment-of-entire-column-in-a-table

**Comment by eBug** [comment]
@rodolgl http://jsfiddle.net/FufTA/

**Comment by rodolgl** [comment]
Ya claro, pero no hay modo de que el CSS sepa que la columna es numérica o un string para ponerlo de un modo u otro. De ese modo se puede hacer una "facilitación" de cuadrarlo, pero no deja de ser un modo que hay que asignarlo cada vez que se ponga una columna numérica. Es mejor poner una class que hacer un style dentro del campo de la tabla, pero no es la solución óptima. Como dije, únicamente facilita ponerlo, pero hay que ponerlo desgraciadamente.

**Comment by eBug** [comment]
@rodolgl la solución con <table class="tr2 tc3 tr7"> me parece bastante fácil de usar, no ?

**Comment by rodolgl** [comment]
Arreglado. Se cierra y se verá  en el próximo commit.
