### ISSUE TITLE
operaciones view_trafico()

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#341]
Error: syntax error, unexpected '}'
File: C:\xampp\htdocs\cake-cmpsa\app\View\Operaciones\view_trafico.ctp
Line: 205

**Comment by eBug** [comment]
En test/ me parece estar solucinado. Si quieres lo compruebas y lo cierras. Desde aquí no veo errores (ni en acer, ni en kona).

**Comment by rodolgl** [comment]
Funciona jefe! Cierro!
