### ISSUE TITLE
Error al agregar cuenta de almacen en la base de datos. almacen_transportes/add/from_controller:transportes/from_id:73

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#342]
Database Error

Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'created' in 'field list'

SQL Query: INSERT INTO `cmpsa_migration`.`almacen_transportes` (`almacen_id`, `cuenta_almacen`, `cantidad_cuenta`, `peso_bruto`, `marca_almacen`, `transporte_id`, `modified`, `created`) VALUES (58, '32131', 1, 1, '', 73, '2016-05-19 15:07:40', '2016-05-19 15:07:40')

Notice: If you want to customize this error message, create app/View/Errors/pdo_error.ctp

**Comment by eBug** [comment]
el error viene del trigger, debería quedar así:
mysql> select * from almacen_transporte_asociados where almacen_transporte_id=160;
+----+-------------+-----------------------+-----------------+---------------------+----------+
| id | asociado_id | almacen_transporte_id | sacos_asignados | created             | modified |
+----+-------------+-----------------------+-----------------+---------------------+----------+
| 47 |          68 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 48 |          77 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 49 |          78 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 50 |          79 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 51 |          80 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 52 |          81 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 53 |          82 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 54 |          83 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
| 55 |          84 |                   160 |               0 | 2016-05-20 13:40:19 | NULL     |
+----+-------------+-----------------------+-----------------+---------------------+----------+
9 rows in set (0.01 sec)

En acer, esta corregido, en kona aun no.

**Comment by eBug** [comment]
mejor aún:
`CREATE DEFINER=`cmpsa`@`localhost` TRIGGER `cmpsa_migration`.`almacen_transportes_AFTER_INSERT` AFTER INSERT ON `almacen_transportes` FOR EACH ROW BEGIN INSERT INTO almacen_transporte_asociados (almacen_transporte_id, asociado_id, sacos_asignados, created, modified ) SELECT a.id, a.asociado_id, a.sacos_asignados, NOW(), NOW() FROM almacen_repartos a WHERE a.id=NEW.id ; END`

**Comment by eBug** [comment]
actualizado en kona también
