### ISSUE TITLE
muestra view()

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#345]
En la lista de líneas falta ver todos los campos a los que despliega. Algunos lo hace y otros no.

**Comment by eBug** [comment]
Se puede ser un poco más preciso?

**Comment by rodolgl** [comment]
Sí, que faltaba en el "Controller" de la función view la AlmacenTransporte y Operacion dentro de LineaMuestra de donde tiraba. Ya está arreglado.
