### ISSUE TITLE
no funciona desplegable de fletes en Operaciones::add()

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#349]
Si ho hay al menos un puerto definido en el contrato, sale el desplegable vacio y nunca mas se vuelve a llenar:
http://cake-cmpsa.gargantilla.net/operaciones/add/from_controller:contratos/from_id:63
Eso pasa en acer, pero igual es porque los precios de flete estan caducados. Hay que mirar si funciona en kona.

**Comment by rodolgl** [comment]
Me borraste las lineas 
	totalPorcentaje +=porcentajeAsociado;
-    }
-    textototalCantidad.innerHTML = totalCantidad;
-    textototalPorcentaje.innerHTML = totalPorcentaje.toFixed(2) + "%";
