### ISSUE TITLE
Cuenta de almacén no se puede eliminar por clave foránea. Crear control si hay línea para no permitir borrar como en retiradas

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#365]
/almacen_transportes/delete/12

Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`cmpsa_migration`.`linea_muestras`, CONSTRAINT `fk_linea_muestras_almacen_transportes1` FOREIGN KEY (`almacen_transporte_id`) REFERENCES `almacen_transportes` (`id`) ON DELETE NO ACTION ON

**Comment by eBug** [comment]
metiste un beforeDelete ?

**Comment by rodolgl** [comment]
No, he metido un **if** para que no se vean los botones en caso que haya retiradas o linea de muestra. Más limpio que dejar botones que no se pueden usar.

**Comment by eBug** [comment]
@rodolgl Lo suyo es tener los dos, el no estar el botón no impide que se acceda a la función directamente por la URL.
