### ISSUE TITLE
Carlos no puede enviar informes

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#407]
http://gestion.cmpsa.com/linea_muestras/info_envio/36

/var/www/cake-cmpsa/app/Config/email.php not found.

Error: Ha ocurrido un error interno.

**Comment by rodolgl** [comment]
Esto es normal. Ese archivo tiene que meterse en el servidor para que funcione el correo. Se ignoró en el github porque hay contraseñas dentro de él.
Lo subo a kona y cierro esto.

**Comment by rodolgl** [comment]
Agregado. Falta que se hagan pruebas de nuevo.

**Comment by rodolgl** [comment]
File not found: "/var/www/cake-cmpsa/app/webroot/files/Informes/EN-3_20160726.pdf"

**Comment by rodolgl** [comment]
Parece que es una cuestión de permisos se pone la carpeta Informes en 775. Luego una cuestión de contraseñas del correo. Me funciona. Esperando confirmación Carlos.

**Comment by rodolgl** [comment]
Comprobado. Funciona. Falta maquetación que no funciona en Kona. Eso es otro tiquet. Cierro.
