### ISSUE TITLE
Incompatibilidad de CakePHP 2.7 con PHP7.0 se corrige con la versión 2.8

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#414]
https://github.com/cakephp/cakephp/issues/7671

Tengo mensajes de error en sitios que no tienen sentido. 2.7 funciona con php5.5 o versiones previas.

**Comment by eBug** [comment]
@rodolgl kona usa php 5.6

**Comment by rodolgl** [comment]
Eso acabo de hacer. Una ppa que vi y en eso estamos.  Ya funciona todo. Cierro.
