### ISSUE TITLE
La vista de asociados no funciona.

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#418]
Error: Call to undefined function bcmod()
File: /var/www/html/cake-cmpsa/app/Controller/AppController.php
Line: 198

http://localhost/cake-cmpsa/asociados/view/83

Tampoco funciona en http://pre-cmpsa.gargantilla.net. Ni el index().
Aquí el error es otro:
Error: Call to undefined method AsociadosController::bindCompany()
File: /var/www/cake-cmpsa/app/Controller/AsociadosController.php
Line: 7

**Comment by eBug** [comment]
@rodolgl bcmod() es una función interna de PHP, así que yo comprobaría el PHP instalado.

**Comment by rodolgl** [comment]
Ya rula con un sudo apt-get install php5.6-bcmath
