### ISSUE TITLE
Añadir un campo de tara (peso/bulto) no se sabe en qué tabla

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#444]
Eso sale en facturacion::form()

**Comment by rodolgl** [comment]
Esto aún tiene miga. me dicen en tráfico que ahora sí hace falta tara para enviar a los asociados. a ver que contestan. No hagas de esto por ahora.

**Comment by rodolgl** [comment]
La tara se crea en almacen_transportes.
