### ISSUE TITLE
Tener misma UI en LineaContrato que en LineaMuestra

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#45]
Ser consistente en el funcionamiento de navegación de una parte de la aplicación u otra.
Qué acciones/botones (detalles?)se pueden activan en el listado de lineas de muestras desde Muestra::View()
y qué acciones/botones (borrar,editar?) se deberían dejar en LineaMuestra::View() ?

Lo mismo pasa para Contrato::View() y LineaContrato::View() y seguramente se repita en muchas partes.

**Comment by rodolgl** [comment]
El error esta en el Common View porque le pasa un fromcontroller y sale como si fuera una línea.

**Comment by rodolgl** [comment]
//$this->assign('from_controller','muestras'); Se comenta porque da error a la hora de ver los botones de borrar.
