### ISSUE TITLE
Contratos add errores al guardar

### ISSUE THREAD

**Issue by rodolgl** [Circuletica/cake-cmpsa#461]
![seleccion_001](https://cloud.githubusercontent.com/assets/8113818/18631598/3ec8589e-7e73-11e6-9313-b8219f0259a1.png)

Error: SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`cmpsa`.`contratos`, CONSTRAINT `fk_contratos_canal_compras1` FOREIGN KEY (`canal_compra_id`) REFERENCES `canal_compras` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION)

**Comment by eBug** [comment]
@rodolgl Si no está la tabla en la base de datos...

**Comment by rodolgl** [comment]
Solventado.
