### ISSUE TITLE
corregir columnas de tabla operacion_venta_cuentas

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#483]
+------------------------+-------------+------+-----+---------+----------------+
| Field                  | Type        | Null | Key | Default | Extra          |
+------------------------+-------------+------+-----+---------+----------------+
| id                     | int(11)     | NO   | PRI | NULL    | auto_increment |
| operacion_ventas_id    | int(11)     | NO   | MUL | NULL    |                |
| almacen_transportes_id | int(11)     | NO   | MUL | NULL    |                |
| cantidad               | smallint(6) | NO   |     | NULL    |                |
| created                | datetime    | YES  |     | NULL    |                |
| modified               | datetime    | YES  |     | NULL    |                |
+------------------------+-------------+------+-----+---------+----------------+

**Comment by rodolgl** [comment]
Está corregido pero operacion_venta_id está deshabilitado el NOT NULL porque sino daba error. Dejo el issue abierto hasta que lo relacionemos bien.

**Comment by eBug** [comment]
@rodolgl el único problema que tenía era el nombre erróneo de las columna y era complicado corregirlo por línea de comando. Se puede cerrar
