### ISSUE TITLE
Concretar orden de los campos en Linea Muestra

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#6]
En LineaMuestra::view() hay que justificar las cribas a la derecha

**Comment by rodolgl** [comment]
Esto al final lo hablé con Carlos y me dijo que cuando tuviera tiempo hacíamos un esquema de cómo quería tener los campos colocados. Lo dejo abierto con otro título.

**Comment by rodolgl** [comment]
Carlos me pasó un esquema, pero por ahora no es urgente.

**Comment by eBug** [comment]
Podemos cerrar este ? Carlos esta ahora trabajando con un formato del que no se esta quejando

**Comment by rodolgl** [comment]
Lo cierro. Cuando esté todo montado voy vista por vista repasandolas.
