### ISSUE TITLE
View/Layout/default.ctp tira de un css externo

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#72]
echo $this->Html->css('//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css');

mejor tener el archivo en local, porque deja de funcionar la aplicación cuando no hay conexión a internet.

**Comment by rodolgl** [comment]
Voy a descargarme el archivo, además hay una nueva versión. Cuando termine, actualizo y cierro.

**Comment by rodolgl** [comment]
Se descarga en local y se hace commit.
