### ISSUE TITLE
Falla el añadir lineas a las muestras por un tema de cribas

### ISSUE THREAD

**Issue by eBug** [Circuletica/cake-cmpsa#88]

**Comment by eBug** [comment]
hay un error de indices al pulsar en 'guardar linea'

**Comment by eBug** [comment]
Al formatear la pantalla, se han quedado los campos de criba fuera del formulario:

$this->Form->end() aparece antes de los Form->input de criba.
Ojo que no puede haber una tabla dentro de un formulario.

**Comment by rodolgl** [comment]
Error mío de libro. Se ha formateado en columnas. Falta por formatear de manera más amigable. Ya guarda las líneas adecuadamente.
